# Form implementation generated from reading ui file 'view\ui\frmCodeListing.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_code_listing_form(object):
    def setupUi(self, code_listing_form):
        code_listing_form.setObjectName("code_listing_form")
        code_listing_form.resize(1156, 754)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(code_listing_form.sizePolicy().hasHeightForWidth())
        code_listing_form.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(code_listing_form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.line_code_list_name = QtWidgets.QLineEdit(code_listing_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_code_list_name.sizePolicy().hasHeightForWidth())
        self.line_code_list_name.setSizePolicy(sizePolicy)
        self.line_code_list_name.setObjectName("line_code_list_name")
        self.horizontalLayout.addWidget(self.line_code_list_name)
        self.pbtn_create_new_code_list = QtWidgets.QPushButton(code_listing_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtn_create_new_code_list.sizePolicy().hasHeightForWidth())
        self.pbtn_create_new_code_list.setSizePolicy(sizePolicy)
        self.pbtn_create_new_code_list.setToolTip("")
        self.pbtn_create_new_code_list.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("view\\ui\\../images/icons/plus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_create_new_code_list.setIcon(icon)
        self.pbtn_create_new_code_list.setObjectName("pbtn_create_new_code_list")
        self.horizontalLayout.addWidget(self.pbtn_create_new_code_list)
        self.pbtn_delete_code_list = QtWidgets.QPushButton(code_listing_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbtn_delete_code_list.sizePolicy().hasHeightForWidth())
        self.pbtn_delete_code_list.setSizePolicy(sizePolicy)
        self.pbtn_delete_code_list.setToolTip("")
        self.pbtn_delete_code_list.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("view\\ui\\../images/icons/clear.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_delete_code_list.setIcon(icon1)
        self.pbtn_delete_code_list.setObjectName("pbtn_delete_code_list")
        self.horizontalLayout.addWidget(self.pbtn_delete_code_list)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.wtree_code_list = QtWidgets.QTreeWidget(code_listing_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wtree_code_list.sizePolicy().hasHeightForWidth())
        self.wtree_code_list.setSizePolicy(sizePolicy)
        self.wtree_code_list.setObjectName("wtree_code_list")
        self.wtree_code_list.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.wtree_code_list)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.wtable_code_list = QtWidgets.QTableWidget(code_listing_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wtable_code_list.sizePolicy().hasHeightForWidth())
        self.wtable_code_list.setSizePolicy(sizePolicy)
        self.wtable_code_list.setObjectName("wtable_code_list")
        self.wtable_code_list.setColumnCount(0)
        self.wtable_code_list.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.wtable_code_list)

        self.retranslateUi(code_listing_form)
        QtCore.QMetaObject.connectSlotsByName(code_listing_form)

    def retranslateUi(self, code_listing_form):
        _translate = QtCore.QCoreApplication.translate
        code_listing_form.setWindowTitle(_translate("code_listing_form", "Code Listing"))
